#ifndef __SOUND_ID_H__
#define __SOUND_ID_H__


typedef enum RES_SOUND_ID
{
	RES_SOUND_ID_NONE = -1,
	RES_SOUND_ID_MIN = 0,

	RES_SOUND_ID_MUSIC_MIN = RES_SOUND_ID_MIN,

	RES_SOUND_ID_MUSIC_MAIN = RES_SOUND_ID_MUSIC_MIN,
	RES_SOUND_ID_MUSIC_GAME,
	RES_SOUND_ID_MUSIC_MAX,

	RES_SOUND_ID_SOUND_MIN = RES_SOUND_ID_MUSIC_MAX,


	RES_SOUND_ID_SOUND_MAX,
	RES_SOUND_ID_MAX = RES_SOUND_ID_SOUND_MAX
};




#endif


